Local dir for gnu global tags:

GNU global: https://www.gnu.org/software/global/

Emacs package: https://github.com/leoliu/ggtags

Emacs package for helm: https://github.com/emacsorphanage/helm-gtags (install it if you are helm user)

We can use both packages independly.

* installation

-- remove all =*tags= packages on your OS. They can cause errors, be outdated or misconfigured.
We will use tagging systems directly: via emacs and this local directory.

Arch Linux:

#+BEGIN_SRC 
sudo pacman -Rns global
sudo pacman -R ctags
sudo pacman -R etags
#+END_SRC

-- mkdir:

#+begin_src emacs-lisp
mkdir -p ~/.emacs.d/ggtags/src/ctags
#+end_src

-- compile and install =universal-ctags= - https://github.com/universal-ctags/ctags

#+begin_src emacs-lisp
git clone https://github.com/universal-ctags/ctags.git ~/.emacs.d/ggtags/src/ctags
cd ~/.emacs.d/ggtags/src/ctags
./autogen.sh
./configure --prefix=$HOME/.emacs.d/ggtags
make
make install
#+end_src

-- compile and install =gnu-global= - https://www.gnu.org/software/global/

Please be aware that GNU Global is not using git as version control system. Instead of that, we need to download it manually from ftp server. The pygments plugin has been included in GNU Global since version =6.3.2= (so =pip install pygments= is no more required).

#+begin_src emacs-lisp
cd ~/.emacs.d/ggtags/src
wget https://ftp.gnu.org/pub/gnu/global/global-6.6.8.tar.gz
# OPTIONAL TODO: verify downloaded file via .sig
tar xzvf ./global-6.6.8.tar.gz
rm ./global-6.6.8.tar.gz
# Compile and install gnu global with universal-ctags:
./configure --prefix=$HOME/.emacs.d/ggtags --with-universal-ctags=$HOME/.emacs.d/ggtags/bin/ctags
#+end_src

-- install, check and update =gtags.conf= file:

#+begin_src emacs-lisp
cd ~/.emacs.d/ggtags/src/global-6.6.8
cp ./gtags.conf $HOME/.emacs.d/ggtags/
#+end_src

*OPTIONAL* - merge some parsers into one label; add this somewhere at the beginning into =$HOME/.emacs.d/ggtags/gtags.conf=:

#+BEGIN_EXAMPLE
universalctags-pygments-native:\
	:tc=universal-ctags:tc=pygments-parser:tc=builtin-parser:
#+END_EXAMPLE

*universal-ctags* seems to be most updated and written in =C= (it means fastest one) - so that one we will use with higher priority.

*pygments* plugin is written in =python=, so it could be slower than *universalctags*.

-- customize your elisp with below code:

#+begin_src emacs-lisp
;; customize PATH and exec-path:

(setenv "PATH" (concat (concat (getenv "HOME") "/.emacs.d/ggtags/bin") path-separator (getenv "PATH")))
(add-to-list 'exec-path (concat (getenv "HOME") "/.emacs.d/ggtags/bin"))

;; now we can manipulate with GTAGS* env variables:

(setenv "GTAGSCONF" (concat (getenv "HOME") "/.emacs.d/ggtags/gtags.conf"))
(setenv "GTAGSLABEL" "new-ctags") ;; it means "universal-ctags" only as default, this option is faster than "pygments"
;; (setenv "GTAGSLABEL" "pygments") ;; if "universal-ctags" will not be enough, then "pygments" can cover less popular languages
;; (setenv "GTAGSLABEL" "universalctags-pygments-native") ;; that config is slow for big codebase, use it only for small projects...
#+end_src

For more env variables, please see man:  https://www.gnu.org/software/global/manual/global.html#ENVIRONMENT

-- *OPTIONAL*: if you like to use ggtags outside your emacs, then add this into the =$PATH= (env variable):

#+BEGIN_EXAMPLE
export PATH="$PATH:$HOME/.emacs.d/ggtags/bin"
#+END_EXAMPLE
