(load (expand-file-name "elisp/init_core.el" user-emacs-directory))

;; Common packages:
(use-package cfg-op-quelpa)
(use-package cfg-op-completion-systems) ;; must be loaded before company
(use-package cfg-op-company) ;; company should be FIRST, because after that some variables will be overwritten via lsp-bridge
(use-package cfg-op-yasnippets)
(use-package cfg-op-list-auto-mode-alist)
(use-package cfg-op-core-dark-theme)
(use-package cfg-op-fonts)
(use-package cfg-op-core-mode-line)
(use-package cfg-op-tree-sitter)
(use-package cfg-op-perspective)
(use-package cfg-op-copy-paste)
(use-package cfg-op-pgtk)
(use-package cfg-op-treemacs-speedbar)
(use-package cfg-op-dumbjump)
(use-package cfg-op-epm)
(use-package cfg-op-evil)
(use-package cfg-op-dired)
(use-package cfg-op-webpaste-htmlize)
(use-package cfg-op-line-numbers)
(use-package cfg-op-email)
(use-package cfg-op-vterm)

;; Langs:
(use-package cfg-op-magit)
(use-package cfg-op-format)
(use-package cfg-op-python)
(use-package cfg-op-fish)
(use-package cfg-op-lua)
(use-package cfg-op-ssh-config)
(use-package cfg-op-flycheck)
(use-package cfg-op-markdown)
(use-package cfg-op-json)
(use-package cfg-op-groovy-jenkins)
(use-package cfg-op-nix)
(use-package cfg-op-php)
(use-package cfg-op-org)
(use-package cfg-op-yaml)
(use-package cfg-op-emmet)
(use-package cfg-op-web-mode)

;; LSP -> must be defined after languages and tree-sitter
(use-package cfg-op-lsp-bridge)
