(add-to-list 'load-path (expand-file-name "elisp" user-emacs-directory)) ; additional/optional load-path will be configured in cfg-use-package

(require 'cfg-performance-native-comp)
(require 'cfg-use-package)
(require 'cfg-list-pure-packages)
(require 'cfg-list-auto-mode-alist)
(require 'cfg-diagnose)
(require 'cfg-common-options)
(require 'cfg-line-numbers)
(require 'cfg-evil)
(require 'cfg-ediff-diff-vdiff)
(require 'cfg-formatting)
(require 'cfg-tree-sitter)
(require 'cfg-grep-recentf)
;; (require 'cfg-projectile)
(require 'cfg-project)
(require 'cfg-fly-modes)
(require 'cfg-i-buffer-menu)
(require 'cfg-persp-desktop)
(require 'cfg-markdown)
(require 'cfg-json-xml)
(require 'cfg-web-front-end)
(require 'cfg-folding-hideshow)
(require 'cfg-tabs)
(require 'cfg-dired)
(require 'cfg-treemacs-speedbar)
(require 'cfg-ggtags-dumbjump)
(require 'cfg-pdf-tools-doc-view)
(require 'cfg-perl-regexps)
(require 'cfg-php)
(require 'cfg-groovy-jenkins)
(require 'cfg-vcs-magit)
(require 'cfg-webpaste-browsers)
(require 'cfg-python)
(require 'cfg-yasnippets)
(require 'cfg-company)
(require 'cfg-corfu)
(require 'cfg-os-linux-tools)
(require 'cfg-tramp-sudo-ssh)
(require 'cfg-e-shell-terminals)
(require 'cfg-general-which-keys)
(require 'cfg-completion-systems)
;; (require 'cfg-completion-systems-native)
(require 'cfg-lsp-dap)
(require 'cfg-custom-file)
(require 'cfg-themes-fonts)
(require 'cfg-mode-line-hl)
