* GNU Global tags

GNU global: https://www.gnu.org/software/global/  

Emacs package: https://github.com/leoliu/ggtags  

** installation

-- remove all =*tags= packages on your OS. They can cause errors, be outdated or misconfigured.
We will use tagging systems directly - via emacs and this local directory.

For example in Arch Linux:

#+BEGIN_SRC 
sudo pacman -Rns global
sudo pacman -R ctags
sudo pacman -R etags
#+END_SRC

-- mkdir:

#+begin_src emacs-lisp
mkdir -p ~/.emacs.d/data/tools/src/ctags
#+end_src

-- compile and install =universal-ctags= - https://github.com/universal-ctags/ctags

#+begin_src emacs-lisp
git clone https://github.com/universal-ctags/ctags.git ~/.emacs.d/data/tools/src/ctags
cd ~/.emacs.d/data/tools/src/ctags
./autogen.sh
./configure --prefix=$HOME/.emacs.d/data/tools
make && make install
#+end_src

-- compile and install =gnu-global= - https://www.gnu.org/software/global/

Please be aware that GNU Global is not using git as version control system. Instead of that, we need to download it manually from ftp server. The =pygments= plugin has been included in GNU Global since version =6.3.2= (so =pip install pygments= is no more required).

Set GNU Global latest version (only for that one shell session):

#+begin_src emacs-lisp
export GTAGSFTPVERSION=6.6.13
#+end_src

When your version will be set, then go ahead with whole installation:

#+begin_src emacs-lisp
cd ~/.emacs.d/data/tools/src
wget https://ftp.gnu.org/pub/gnu/global/global-$GTAGSFTPVERSION.tar.gz
# OPTIONAL TODO: verify downloaded file via .sig
tar xzvf ./global-$GTAGSFTPVERSION.tar.gz
rm ./global-$GTAGSFTPVERSION.tar.gz
# Compile and install gnu global with universal-ctags:
cd $HOME/.emacs.d/data/tools/src/global-$GTAGSFTPVERSION
./configure --prefix=$HOME/.emacs.d/data/tools --with-universal-ctags=$HOME/.emacs.d/data/tools/bin/ctags
make && make install
#+end_src

-- install, check and update =gtags.conf= file:

#+begin_src emacs-lisp
cd ~/.emacs.d/data/tools/src/global-$GTAGSFTPVERSION
cp ./gtags.conf $HOME/.emacs.d/data/tools/
#+end_src

*OPTIONAL* - merge some parsers into one label; add this somewhere at the beginning into =$HOME/.emacs.d/data/tools/gtags.conf=:

#+BEGIN_EXAMPLE
universalctags-pygments-native:\
	:tc=universal-ctags:tc=pygments-parser:tc=builtin-parser:
#+END_EXAMPLE

*universal-ctags* seems to be most updated and written in =C= (it means fastest one) - so that one we will use with higher priority.

*pygments* plugin is written in =python=, so it could be slower than *universal-ctags*.

-- customize your elisp with below code:

#+begin_src emacs-lisp
;; GTAGS* env variables:

(setenv "GTAGSCONF" (concat (getenv "HOME") "/.emacs.d/data/tools/gtags.conf"))

;; choose one of available labek (ggtags backend):
(setenv "GTAGSLABEL" "new-ctags") ;; it means "universal-ctags" only as default, this option is faster than "pygments"
;; (setenv "GTAGSLABEL" "pygments") ;; if "universal-ctags" will not be enough, then "pygments" can cover less popular languages
;; (setenv "GTAGSLABEL" "universalctags-pygments-native") ;; that config is slow for big codebase, use it only for small projects...
#+end_src

-- *OPTIONAL*: if you like to use =gtags= cmd outside your emacs, then add this env variables into your system:

#+BEGIN_EXAMPLE
export GTAGSCONF=$HOME/.emacs.d/data/tools/gtags.conf

# and now choose one of available label/backend:
export GTAGSLABEL=new-ctags
# export GTAGSLABEL=new-ctags
# export GTAGSLABEL=universalctags-pygments-native
#+END_EXAMPLE

For more env variables, please see man:  https://www.gnu.org/software/global/manual/global.html#ENVIRONMENT
