;;; cfg-op-core-dark-theme.el --- configuration for built-in themes in emacs -*- lexical-binding: t -*-
;;; Commentary:
;;
;;; Code:

(defcustom emacs-cfg-use-custom-theme 'modusdisco
  ;; (defcustom emacs-cfg-use-custom-theme 'crafters
  "Select which `emacs-cfg' customization theme to use.

- nil: Disable custom theme
- 'catppuccin: Use customizations for Catppuccin
- 'crafters: Use customizations for the Crafters theme
- 'modusdisco: A more colorful version of Modus"
  :type '(choice
          (const :tag "Disabled" nil)
          (const :tag "Catppuccin" catppuccin)
          (const :tag "ModusDisco" modusdisco)
          (const :tag "Crafters" crafters))
  :group 'emacs-cfg)

;;; Older but currently not recommended:
;;
;; (load-theme 'misterioso t)
;; (load-theme 'wombat t)
;; (load-theme 'tango-dark t)

;;; Catppuccin Theme (hacked Modus)
(use-package modus-themes
  :if (eq emacs-cfg-use-custom-theme 'catppuccin)
  :ensure nil
  :defer t
  :custom
  (modus-themes-italic-constructs t)
  (modus-themes-bold-constructs t)
  (modus-themes-mixed-fonts nil)
  (modus-themes-prompts '(bold intense))
  (modus-themes-common-palette-overrides
   `((accent-0 "#89b4fa")
     (accent-1 "#89dceb")
     (bg-active bg-main)
     (bg-added "#364144")
     (bg-added-refine "#4A5457")
     (bg-changed "#3e4b6c")
     (bg-changed-refine "#515D7B")
     (bg-completion "#45475a")
     (bg-completion-match-0 "#1e1e2e")
     (bg-completion-match-1 "#1e1e2e")
     (bg-completion-match-2 "#1e1e2e")
     (bg-completion-match-3 "#1e1e2e")
     (bg-hl-line "#2a2b3d")
     (bg-hover-secondary "#585b70")
     (bg-line-number-active unspecified)
     (bg-line-number-inactive "#1e1e2e")
     (bg-main "#1e1e2e")
     (bg-mark-delete "#443245")
     (bg-mark-select "#3e4b6c")
     (bg-mode-line-active "#181825")
     (bg-mode-line-inactive "#181825")
     (bg-prominent-err "#443245")
     (bg-prompt unspecified)
     (bg-prose-block-contents "#313244")
     (bg-prose-block-delimiter bg-prose-block-contents)
     (bg-region "#585b70")
     (bg-removed "#443245")
     (bg-removed-refine "#574658")
     (bg-tab-bar      "#1e1e2e")
     (bg-tab-current  bg-main)
     (bg-tab-other    "#1e1e2e")
     (border-mode-line-active nil)
     (border-mode-line-inactive nil)
     (builtin "#89b4fa")
     (comment "#9399b2")
     (constant  "#f38ba8")
     (cursor  "#f5e0dc")
     (date-weekday "#89b4fa")
     (date-weekend "#fab387")
     (docstring "#a6adc8")
     (err     "#f38ba8")
     (fg-active fg-main)
     (fg-completion "#cdd6f4")
     (fg-completion-match-0 "#89b4fa")
     (fg-completion-match-1 "#f38ba8")
     (fg-completion-match-2 "#a6e3a1")
     (fg-completion-match-3 "#fab387")
     (fg-heading-0 "#f38ba8")
     (fg-heading-1 "#fab387")
     (fg-heading-2 "#f9e2af")
     (fg-heading-3 "#a6e3a1")
     (fg-heading-4 "#74c7ec")
     (fg-line-number-active "#b4befe")
     (fg-line-number-inactive "#7f849c")
     (fg-link  "#89b4fa")
     (fg-main "#cdd6f4")
     (fg-mark-delete "#f38ba8")
     (fg-mark-select "#89b4fa")
     (fg-mode-line-active "#bac2de")
     (fg-mode-line-inactive "#585b70")
     (fg-prominent-err "#f38ba8")
     (fg-prompt "#cba6f7")
     (fg-prose-block-delimiter "#9399b2")
     (fg-prose-verbatim "#a6e3a1")
     (fg-region "#cdd6f4")
     (fnname    "#89b4fa")
     (fringe "#1e1e2e")
     (identifier "#cba6f7")
     (info    "#94e2d5")
     (keyword   "#cba6f7")
     (keyword "#cba6f7")
     (name "#89b4fa")
     (number "#fab387")
     (property "#89b4fa")
     (string "#a6e3a1")
     (type      "#f9e2af")
     (variable  "#fab387")
     (warning "#f9e2af")))
  :config
  (modus-themes-with-colors
    (custom-set-faces
     `(change-log-acknowledgment ((,c :foreground "#b4befe")))
     `(change-log-date ((,c :foreground "#a6e3a1")))
     `(change-log-name ((,c :foreground "#fab387")))
     `(diff-context ((,c :foreground "#89b4fa")))
     `(diff-file-header ((,c :foreground "#f5c2e7")))
     `(diff-header ((,c :foreground "#89b4fa")))
     `(diff-hunk-header ((,c :foreground "#fab387")))
     `(gnus-button ((,c :foreground "#8aadf4")))
     `(gnus-group-mail-3 ((,c :foreground "#8aadf4")))
     `(gnus-group-mail-3-empty ((,c :foreground "#8aadf4")))
     `(gnus-header-content ((,c :foreground "#7dc4e4")))
     `(gnus-header-from ((,c :foreground "#cba6f7")))
     `(gnus-header-name ((,c :foreground "#a6e3a1")))
     `(gnus-header-subject ((,c :foreground "#8aadf4")))
     `(log-view-message ((,c :foreground "#b4befe")))
     `(match ((,c :background "#3e5768" :foreground "#cdd6f5")))
     ;; :foreground "#cdd6f4" -- Catppuccin default, not that visible...
     `(modus-themes-search-current ((,c :background "#f38ba8" :foreground "#11111b" )))
     ;; :foreground "#cdd6f4" :background "#94e2d5" -- Catppuccin default, not that visible...
     `(modus-themes-search-lazy ((,c :background "#3e5768" :foreground "#cdd6f5")))
     `(newsticker-extra-face ((,c :foreground "#9399b2" :height 0.8 :slant italic)))
     `(newsticker-feed-face ((,c :foreground "#f38ba8" :height 1.2 :weight bold)))
     `(newsticker-treeview-face ((,c :foreground "#cdd6f4")))
     `(newsticker-treeview-selection-face ((,c :background "#3e5768" :foreground "#cdd6f5")))
     `(tab-bar ((,c :background "#1e1e2e" :foreground "#bac2de")))
     `(tab-bar-tab ((,c :background "#1e1e2e" :underline t)))
     `(tab-bar-tab-group-current ((,c :background "#1e1e2e" :foreground "#bac2de" :underline t)))
     `(tab-bar-tab-group-inactive ((,c :background "#1e1e2e" :foreground "#9399b2"))))
    `(tab-bar-tab-inactive ((,c :background "#1e1e2e" :foreground "#a6adc8")))
    `(vc-dir-file ((,c :foreground "#89b4fa")))
    `(vc-dir-header-value ((,c :foreground "#b4befe"))))
  :init
  (load-theme 'modus-vivendi t))

;;; SystemCrafters Based Theme (hacked Modus)
(use-package modus-themes
  :if (eq emacs-cfg-use-custom-theme 'crafters)
  :ensure nil
  :defer t
  :custom
  (modus-themes-italic-constructs t)
  (modus-themes-bold-constructs t)
  (modus-themes-mixed-fonts nil)
  (modus-themes-prompts '(bold intense))
  (modus-themes-common-palette-overrides
   `((accent-0 "#a1bfff")
     (accent-1 "#79a8ff")
     (bg-active bg-main)
     (bg-added "#2A3B2E")
     (bg-added-refine "#384c3f")
     (bg-changed "#3C435E")
     (bg-changed-refine "#4F5875")
     (bg-completion "#2f447f")
     (bg-completion-match-0 bg-main)
     (bg-completion-match-1 bg-main)
     (bg-completion-match-2 bg-main)
     (bg-completion-match-3 bg-main)
     (bg-hl-line "#30344a")
     (bg-hover-secondary "#676E95")
     (bg-line-number-active unspecified)
     (bg-line-number-inactive "#292D3E")
     (bg-main "#292D3E")
     (bg-mark-delete "#4d2d2d")
     (bg-mark-select "#3C435E")
     (bg-mode-line-active "#232635")
     (bg-mode-line-inactive "#282c3d")
     (bg-prominent-err "#4d2d2d")
     (bg-prompt unspecified)
     (bg-prose-block-contents "#232635")
     (bg-prose-block-delimiter bg-prose-block-contents)
     (bg-region "#3C435E")
     (bg-removed "#4d2d2d")
     (bg-removed-refine "#603939")
     (bg-tab-bar      "#292D3E")
     (bg-tab-current  bg-main)
     (bg-tab-other    "#292D3E")
     (border-mode-line-active nil)
     (border-mode-line-inactive nil)
     (builtin "#82aaff")
     (comment "#676E95")
     (constant  "#f78c6c")
     (cursor  "#EEFFFF")
     (date-weekday "#82aaff")
     (date-weekend "#f78c6c")
     (docstring "#8d92af")
     (err     "#ff5370")
     (fg-active fg-main)
     (fg-completion "white")
     (fg-completion-match-0 "#82aaff")
     (fg-completion-match-1 "#ff5370")
     (fg-completion-match-2 "#c3e88d")
     (fg-completion-match-3 "#f78c6c")
     (fg-heading-0 "#82aaff")
     (fg-heading-1 "#82aaff")
     (fg-heading-2 "#c792ea")
     (fg-heading-3 "#bb80b3")
     (fg-heading-4 "#a1bfff")
     (fg-line-number-active fg-main)
     (fg-line-number-inactive "gray50")
     (fg-link  "#82aaff")
     (fg-main "#EEFFFF")
     (fg-mark-delete "#ff5370")
     (fg-mark-select "#82aaff")
     (fg-mode-line-active "#A6Accd")
     (fg-mode-line-inactive "#676E95")
     (fg-prominent-err "#ff5370")
     (fg-prompt "#c792ea")
     (fg-prose-block-delimiter "#676E95")
     (fg-prose-verbatim "#c3e88d")
     (fg-region "white")
     (fnname    "#82aaff")
     (fringe "#292D3E")
     (identifier "#c792ea")
     (info    "#89DDFF")
     (keyword   "#89DDFF")
     (name "#82aaff")
     (number "#f78c6c")
     (property "#82aaff")
     (string "#c3e88d")
     (type      "#c792ea")
     (variable  "#c792ea")
     (warning "#ffcb6b")))
  :config
  (modus-themes-with-colors
    (custom-set-faces
     `(change-log-acknowledgment ((,c :foreground "#a1bfff")))
     `(change-log-date ((,c :foreground "#c3e88d")))
     `(change-log-name ((,c :foreground "#f78c6c")))
     `(diff-context ((,c :foreground "#82aaff")))
     `(diff-file-header ((,c :foreground "#bb80b3")))
     `(diff-header ((,c :foreground "#82aaff")))
     `(diff-hunk-header ((,c :foreground "#f78c6c")))
     `(gnus-button ((,c :foreground "#82aaff")))
     `(gnus-group-mail-3 ((,c :foreground "#82aaff")))
     `(gnus-group-mail-3-empty ((,c :foreground "#82aaff")))
     `(gnus-header-content ((,c :foreground "#89DDFF")))
     `(gnus-header-from ((,c :foreground "#c792ea")))
     `(gnus-header-name ((,c :foreground "#c3e88d")))
     `(gnus-header-subject ((,c :foreground "#82aaff")))
     `(log-view-message ((,c :foreground "#a1bfff")))
     `(match ((,c :background "#3C435E" :foreground "#EEFFFF")))
     `(modus-themes-search-current ((,c :background "#ff5370" :foreground "#292D3E" )))
     `(modus-themes-search-lazy ((,c :background "#3C435E" :foreground "#EEFFFF")))
     `(newsticker-extra-face ((,c :foreground "#8d92af" :height 0.8 :slant italic)))
     `(newsticker-feed-face ((,c :foreground "#ff5370" :height 1.2 :weight bold)))
     `(newsticker-treeview-face ((,c :foreground "#EEFFFF")))
     `(newsticker-treeview-selection-face ((,c :background "#3C435E" :foreground "#EEFFFF")))
     `(tab-bar ((,c :background "#292D3E" :foreground "#A6Accd")))
     `(tab-bar-tab ((,c :background "#292D3E" :underline t)))
     `(tab-bar-tab-group-current ((,c :background "#292D3E" :foreground "#A6Accd" :underline t)))
     `(tab-bar-tab-group-inactive ((,c :background "#292D3E" :foreground "#777")))
     `(tab-bar-tab-inactive ((,c :background "#292D3E" :foreground "#676E95")))
     `(vc-dir-file ((,c :foreground "#82aaff")))
     `(vc-dir-header-value ((,c :foreground "#a1bfff")))))
  :init
  (load-theme 'modus-vivendi-tinted t))

;;; Modus disco (a more colorful version of Modus)
(use-package modus-themes
  :if (eq emacs-cfg-use-custom-theme 'modusdisco)
  :ensure nil
  :defer t
  :custom
  (modus-themes-italic-constructs t)
  (modus-themes-bold-constructs t)
  (modus-themes-mixed-fonts nil)
  (modus-themes-prompts '(bold intense))
  (modus-themes-common-palette-overrides
   `((bg-tab-bar      "#1e1e2e")
     (bg-tab-current  "#1e1e2e")
     (bg-tab-other    "#1e1e2e")
     (bg-mode-line-active "#181825")
     (bg-mode-line-inactive "#181825")
     (border-mode-line-active nil)
     (border-mode-line-inactive nil)))
  :config
  ;;
  (set-face-attribute 'default nil :height 130)
  ;;;; mode-line
  (set-face-background #'mode-line "DeepPink4")
  (set-face-foreground #'mode-line "yellow")
  ;; (set-face-background #'mode-line-inactive "white")
  ;; (set-face-background #'mode-line-inactive "burlywood")
  ;; (set-face-foreground #'mode-line-inactive "black")
  ;;
  ;; `custom-set-faces' compatible with modus-vivendi dark themes:
  (custom-set-faces
   ;; mode-line
   ;; '(border-mode-line-active ((t (:box nil))))
   ;; '(border-mode-line-inactive ((t (:box nil))))
   ;; tab-bar
   '(tab-bar ((t (:background "#1e1e2e" :foreground "#bac2de"))))
   '(tab-bar-tab ((t (:background "#1e1e2e" :underline t))))
   '(tab-bar-tab-group-current ((t (:background "#1e1e2e" :foreground "#bac2de" :underline t))))
   '(tab-bar-tab-group-inactive ((t (:background "#1e1e2e" :foreground "#9399b2"))))
   '(tab-bar-tab-inactive ((t (:background "#1e1e2e" :foreground "#a6adc8"))))
   ;;
   '(dired-mark ((t nil)))
   '(dired-marked ((t (:foreground "DarkOrange" :weight bold))))
   '(erc-button ((t (:background "gray0" :foreground "dodger blue" :underline "dodger blue" :weight bold))))
   '(erc-default-face ((t (:background "gray7" :foreground "yellow"))))
   '(erc-direct-msg-face ((t (:foreground "wheat"))))
   '(erc-input-face ((t (:foreground "red"))))
   '(erc-inverse-face ((t (:background "Black" :foreground "yellow"))))
   '(erc-keyword-face ((t (:background "lawn green" :foreground "medium blue" :weight bold))))
   '(erc-my-nick-face ((t (:foreground "red" :weight bold))))
   '(erc-my-nick-prefix-face ((t (:foreground "dark orange" :weight bold))))
   '(erc-nick-default-face ((t (:background "black" :foreground "lawn green" :weight bold))))
   '(erc-nick-msg-face ((t (:foreground "orange red" :weight bold))))
   '(erc-nick-prefix-face ((t (:foreground "dark salmon" :weight bold))))
   '(erc-notice-face ((t (:background "gray21" :foreground "deep sky blue" :weight bold))))
   '(erc-timestamp-face ((t (:foreground "cyan" :weight bold))))
   '(fg:erc-color-face1 ((t (:background "magenta" :foreground "black"))))
   '(font-lock-comment-face ((t (:background "gray15" :foreground "dark orange"))))
   '(font-lock-doc-face ((t (:inherit font-lock-comment-face :background "gray15" :foreground "dark salmon"))))
   '(font-lock-keyword-face ((t (:background "gray0" :foreground "medium sea green"))))
   '(font-lock-type-face ((t (:background "black" :foreground "gold"))))
   '(markdown-markup-face ((t (:background "gray15" :foreground "yellow"))))
   '(notmuch-message-summary-face ((t (:extend t :background "gray11" :foreground "sandy brown"))))
   '(notmuch-search-flagged-face ((t (:background "gray5" :foreground "chartreuse"))))
   '(notmuch-tag-face ((t (:background "navy" :foreground "violet"))))
   '(org-block ((t (:extend t :background "gray8" :foreground "gold"))))
   '(org-block-begin-line ((t (:extend t :foreground "red"))))
   '(org-document-info-keyword ((t (:background "dark blue" :foreground "chocolate"))))
   '(org-drawer ((t (:background "light coral" :foreground "dark violet"))))
   '(org-meta-line ((t (:background "gray16" :foreground "peru" :box (:line-width (1 . 1) :color "magenta" :style released-button)))))
   '(org-verbatim ((t (:background "saddle brown" :foreground "peach puff"))))
   '(rcirc-my-nick ((t (:foreground "red"))))
   '(rcirc-server ((t (:foreground "PaleGreen1"))))
   '(rcirc-timestamp ((t (:inherit default :foreground "magenta"))))
   '(rcirc-url ((t (:foreground "light sky blue" :box nil :underline t :weight bold))))
   '(term-color-blue ((t (:background "deep sky blue" :foreground "DeepSkyBlue1"))))
   '(term-color-cyan ((t (:background "cyan" :foreground "cyan"))))
   '(term-color-green ((t (:background "lawn green" :foreground "lawn green"))))
   '(term-color-magenta ((t (:background "magenta" :foreground "magenta"))))
   '(term-color-red ((t (:background "red1" :foreground "red1"))))
   '(web-mode-comment-face ((t (:inherit font-lock-comment-face :background "gray1"))))
   '(web-mode-doctype-face ((t (:foreground "gray70")))))
  :init
  ;; (load-theme 'modus-vivendi-tinted t) ;; night sky background
  (load-theme 'modus-vivendi t))

(provide 'cfg-op-core-dark-theme)
;;; cfg-op-core-dark-theme.el ends here
